import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD:moneshop/src/app/layout.js
        <Navbar />
=======
        <div className="layout">
          <NavBar />
>>>>>>> 146d7bbead85aa0a7fc7418bfe08acdc3273595a:monadsolar/src/app/layout.js

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
